/* AquaSentinel NER — browser-only prototype logic. No backend or real notifications. */
const STORE = 'aquaSentinelNERReportsV1';
const demoReports = [
  {id:'demo-1',community:'Dibrugarh Community',district:'Dibrugarh',state:'Assam',source:'River',problem:'Flood water contamination',affected:74,date:'2026-08-25',description:'Water appears contaminated after flooding.',risk:'High',score:75,status:'Pending Verification',demo:true,lat:27.4728,lng:94.9120},
  {id:'demo-2',community:'Prototype Community 1',district:'Jorhat',state:'Assam',source:'Pond',problem:'Bad smell',affected:18,date:'2026-08-24',description:'Community observation submitted.',risk:'Moderate',score:40,status:'Verified',demo:true,lat:26.7509,lng:94.2037,verifiedAt:'25 Aug 2026, 10:20 am'},
  {id:'demo-3',community:'Prototype Community 2',district:'Tinsukia',state:'Assam',source:'Hand Pump',problem:'Dirty water',affected:4,date:'2026-08-22',description:'Water condition review requested.',risk:'Low',score:20,status:'Pending Verification',demo:true,lat:27.4890,lng:95.3550}
];
let reports=[], selectedId=null, map=null, markers=[];
const $=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function loadReports(){try{reports=JSON.parse(localStorage.getItem(STORE))||demoReports}catch{reports=demoReports}if(!reports.length)reports=demoReports;selectedId=reports[0].id}
function saveReports(){localStorage.setItem(STORE,JSON.stringify(reports))}
function levelClass(r){return r.toLowerCase()}
function calcRisk(problem,affected,isHealth=false){let score=0, factors=[]; let n=Number(affected)||0;if(n>50){score+=30;factors.push('More than 50 people reported affected (+30)')}else if(n>15){score+=20;factors.push('Several people reported affected (+20)')}else if(n>0){score+=8;factors.push('People affected reported (+8)')}let p=problem.toLowerCase();if(p.includes('flood')){score+=25;factors.push('Flood contamination observed (+25)')}if(p.includes('dirty')||p.includes('colour')){score+=20;factors.push('Water contamination observed (+20)')}if(p.includes('smell')||p.includes('fish')){score+=15;factors.push('Environmental warning observed (+15)')}if(isHealth){score+=18;factors.push('Community health signal recorded (+18)')}score=Math.min(100,score);return{score,factors,risk:score>=55?'High':score>=30?'Moderate':'Low'}}
function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
function setPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.page===page));const names={dashboard:['COMMUNITY OVERVIEW','Good morning, Community Team'],'water-report':['COMMUNITY OBSERVATION','Report a Water Problem'],'health-report':['COMMUNITY HEALTH SIGNAL','Health Report'],'risk':['TRANSPARENT PROTOTYPE LOGIC','Demo Risk Analysis'],'map':['LOCATION VIEW','Community Map'],'alerts':['EARLY WARNING QUEUE','Alerts'],'history':['SAVED IN THIS BROWSER','Reports History'],'about':['ABOUT THE PROTOTYPE','About AquaSentinel NER']};$('#pageEyebrow').textContent=names[page][0];$('#pageTitle').textContent=names[page][1];$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show');if(page==='map')setTimeout(initMap,80);if(page==='risk')renderAnalysis();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){const hi=reports.filter(r=>r.risk==='High').length, mod=reports.filter(r=>r.risk==='Moderate').length, low=reports.filter(r=>r.risk==='Low').length, verified=reports.filter(r=>r.status==='Verified').length;$('#activeAlerts').textContent=hi;$('#highRisk').textContent=hi;$('#reportsCount').textContent=reports.length;$('#verifiedCount').textContent=verified;$('#alertBadge').textContent=hi;$('#bellCount').textContent=hi;$('#lowRiskN').textContent=low;$('#moderateRiskN').textContent=mod;$('#highRiskN').textContent=hi;const max=Math.max(reports.length,1);$('#lowBar').style.width=(low/max*100)+'%';$('#moderateBar').style.width=(mod/max*100)+'%';$('#highBar').style.width=(hi/max*100)+'%';renderRecent();renderHistory();renderAlerts();renderAnalysis()}
function reportRow(r,full=false){return `<div class="recent-row"><span class="report-icon">${r.problem.includes('Health')||r.problem.includes('illness')||r.problem.includes('Fever')||r.problem.includes('Vomiting')?'♡':'⌁'}</span><div><strong>${esc(r.community)} ${r.demo?'<small>Demo Data</small>':''}</strong><p>${esc(r.problem)} · ${esc(r.district)}, ${esc(r.state||'Assam')}</p></div><span class="risk-pill ${levelClass(r.risk)}">${r.risk.toUpperCase()} RISK</span>${full?`<span class="status-pill ${r.status==='Verified'?'verified':''}">${r.status==='Verified'?'✓ VERIFIED':'PENDING'}</span>`:''}</div>`}
function renderRecent(){$('#recentReports').innerHTML=reports.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,4).map(r=>reportRow(r,true)).join('')}
function renderHistory(){$('#historyBody').innerHTML=reports.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(r=>`<tr><td><strong>${esc(r.community)}</strong><small>${esc(r.district)}, ${esc(r.state||'Assam')} ${r.demo?'· Demo Data':''}</small></td><td>${esc(r.problem)}</td><td>${r.affected}</td><td><span class="risk-pill ${levelClass(r.risk)}">${r.risk}</span></td><td><span class="status-pill ${r.status==='Verified'?'verified':''}">${r.status==='Verified'?'✓ Verified':'Pending'}</span></td><td>${formatDate(r.date)}</td><td><div class="action-row"><button class="small-action" onclick="viewReport('${r.id}')">View</button>${r.status!=='Verified'?`<button class="small-action" onclick="verifyReport('${r.id}')">Verify</button>`:''}<button class="small-action delete" onclick="deleteReport('${r.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No reports saved yet.</td></tr>'}
function renderAlerts(){let high=reports.filter(r=>r.risk==='High');$('#alertsList').innerHTML=high.length?high.map(r=>`<article class="card alert-card"><span class="alert-symbol">⚑</span><div><p class="eyebrow">HIGH RISK ALERT ${r.demo?'· DEMO DATA':''}</p><h3>${esc(r.community)}, ${esc(r.state||'Assam')}</h3><p>${esc(r.problem)} report detected. Recommended action: verify local water condition and community report.</p><span class="status-pill ${r.status==='Verified'?'verified':''}">${r.status==='Verified'?'✓ Verified':'Verification Pending'}</span></div><div class="actions">${r.status!=='Verified'?`<button class="outline" onclick="verifyReport('${r.id}')">✓ Verify report</button>`:''}<button class="primary" onclick="simulateAlert('${r.id}')">✉ Simulate notification</button></div></article>`).join(''):'<div class="card empty">No high-risk reports are currently in the prototype queue.</div>'}
function renderAnalysis(){let r=reports.find(x=>x.id===selectedId)||reports[0];if(!r)return;const options=reports.map(x=>`<option value="${x.id}" ${x.id===r.id?'selected':''}>${esc(x.community)} — ${x.risk} risk</option>`).join('');let factors=calcRisk(r.problem,r.affected,r.problem.includes('reports')).factors;if(!factors.length)factors=['No major demo risk condition selected'];$('#analysisPanel').innerHTML=`<div class="selected-report"><p class="eyebrow">CHOOSE A SAVED REPORT</p><select id="analysisSelect">${options}</select></div><div class="score-result"><div class="score-circle" style="--score:${r.score*3.6}deg;--risk:${r.risk==='High'?'var(--red)':r.risk==='Moderate'?'var(--orange)':'var(--green)'}"><b>${r.score}</b><small>OUT OF 100</small></div><div class="score-copy"><p class="eyebrow">DEMO RISK RESULT</p><h3 style="color:${r.risk==='High'?'var(--red)':r.risk==='Moderate'?'var(--orange)':'var(--green)'}">${r.risk.toUpperCase()} RISK</h3><p>${esc(r.community)} · ${esc(r.district)}, ${esc(r.state||'Assam')}</p><button class="outline" onclick="viewReport('${r.id}')">View community report</button></div></div><h3 style="margin-top:28px">Risk factors</h3><ul class="factor-list">${factors.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p class="disclaimer">Next step: verify the report and initiate targeted response if required.</p>`;$('#analysisSelect')?.addEventListener('change',e=>{selectedId=e.target.value;renderAnalysis()})}
function showModal(html){$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.add('show')};function closeModal(){$('#modalBackdrop').classList.remove('show')}
function viewReport(id){let r=reports.find(x=>x.id===id);if(!r)return;showModal(`<div class="success-icon" style="font-size:28px">⌁</div><h2>${esc(r.community)}</h2><p>${r.demo?'Prototype Demonstration Data':'Community report'} · ${formatDate(r.date)}</p><div class="result-summary"><div><span>Problem</span><b>${esc(r.problem)}</b></div><div><span>People affected</span><b>${r.affected}</b></div><div><span>Risk level</span><b class="risk-pill ${levelClass(r.risk)}">${r.risk.toUpperCase()} RISK</b></div><div><span>Status</span><b>${r.status}</b></div></div><div class="modal-actions">${r.status!=='Verified'?`<button class="outline" onclick="verifyReport('${r.id}');closeModal()">✓ Verify report</button>`:''}<button class="primary" onclick="setPage('map');closeModal()">⌖ View on map</button></div>`)}
function verifyReport(id){let r=reports.find(x=>x.id===id);if(!r)return;r.status='Verified';r.verifiedAt=new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});saveReports();renderAll();showModal(`<div class="success-icon">✓</div><h2>Report verified</h2><p>${esc(r.community)} has been marked as verified.<br><small>${r.verifiedAt}</small></p><div class="modal-actions"><button class="primary" onclick="closeModal()">Done</button></div>`)}
function deleteReport(id){let r=reports.find(x=>x.id===id);if(!r||!confirm(`Delete the report for ${r.community}? This can be restored by resetting demo data only.`))return;reports=reports.filter(x=>x.id!==id);if(selectedId===id)selectedId=reports[0]?.id;saveReports();renderAll()}
function simulateAlert(id){let r=reports.find(x=>x.id===id);showModal(`<div class="success-icon">✓</div><h2>Notification prepared</h2><p><b>ALERT READY</b><br>Notification would be sent to:<br><strong>gamesvishva@gmail.com</strong></p><div class="result-summary"><div><span>Community</span><b>${esc(r.community)}</b></div><div><span>Risk</span><b class="risk-pill high">HIGH RISK</b></div><div><span>Sending status</span><b>Prototype simulation only</b></div></div><div class="modal-actions"><button class="primary" onclick="closeModal()">Done</button></div>`)}
function latFor(n){return 26.3+(n%15)*.12}function lngFor(n){return 92.4+(n%17)*.2}
function initMap(){if(!window.L)return;if(!map){map=L.map('mapCanvas').setView([27.15,94.3],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}markers.forEach(m=>m.remove());markers=[];reports.forEach((r,i)=>{let color=r.risk==='High'?'#d95050':r.risk==='Moderate'?'#e98b37':'#279d7b';let icon=L.divIcon({className:'',html:`<div class="risk-marker" style="background:${color}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});let marker=L.marker([r.lat||latFor(i),r.lng||lngFor(i)],{icon}).addTo(map).bindPopup(`<b>${esc(r.community)}</b><br>${esc(r.district)}, ${esc(r.state||'Assam')}<br><strong>${r.risk} risk</strong> · ${r.affected} affected<br>${r.status}`);markers.push(marker)})}
function submitForm(e,isHealth=false){e.preventDefault();let data=Object.fromEntries(new FormData(e.target));let result=calcRisk(data.problem,data.affected,isHealth);let r={id:'r-'+Date.now(),community:data.community.trim(),district:data.district.trim(),state:data.state?.trim()||'Assam',source:data.source||'Community health signal',problem:data.problem,affected:Number(data.affected),date:data.date,description:data.description||'',risk:result.risk,score:result.score,status:'Pending Verification',lat:latFor(reports.length),lng:lngFor(reports.length)};reports.unshift(r);selectedId=r.id;saveReports();renderAll();e.target.reset();$('#photoPreview').innerHTML='';$('#photoText')&&( $('#photoText').textContent='Choose an image (optional)');showModal(`<div class="success-icon">✓</div><h2>Report received</h2><p>Your community report has been recorded.</p><div class="result-summary"><div><span>Community</span><b>${esc(r.community)}</b></div><div><span>Problem</span><b>${esc(r.problem)}</b></div><div><span>People affected</span><b>${r.affected}</b></div><div><span>Demo risk level</span><b class="risk-pill ${levelClass(r.risk)}">${r.risk.toUpperCase()} RISK</b></div><div><span>Status</span><b>Pending Verification</b></div></div><div class="modal-actions"><button class="outline" onclick="closeModal();setPage('history')">View history</button><button class="primary" onclick="closeModal();setPage('risk')">View risk analysis</button></div>`)}
document.addEventListener('DOMContentLoaded',()=>{loadReports();renderAll();document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));$('#menuToggle').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')});$('#overlay').addEventListener('click',()=>{$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')});$('#waterForm').addEventListener('submit',e=>submitForm(e));$('#healthForm').addEventListener('submit',e=>submitForm(e,true));let today=new Date().toISOString().slice(0,10);document.querySelectorAll('input[type=date]').forEach(i=>i.value=today);$('#photoInput').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;$('#photoText').textContent=f.name;let rd=new FileReader();rd.onload=()=>$('#photoPreview').innerHTML=`<img src="${rd.result}" alt="Selected report photo preview">`;rd.readAsDataURL(f)});$('#closeModal').addEventListener('click',closeModal);$('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});$('#clearData').addEventListener('click',()=>{if(confirm('Clear all saved prototype reports and restore the initial demo reports?')){reports=demoReports.map(x=>({...x}));selectedId=reports[0].id;saveReports();renderAll();showModal(`<div class="success-icon">✓</div><h2>Demo data restored</h2><p>The initial prototype reports are ready for your next presentation.</p><div class="modal-actions"><button class="primary" onclick="closeModal()">Done</button></div>`)}})});
window.viewReport=viewReport;window.verifyReport=verifyReport;window.deleteReport=deleteReport;window.simulateAlert=simulateAlert;window.setPage=setPage;window.closeModal=closeModal;

